name: Build macOS Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 手動実行用

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile app.py --name akio-local-engine
        
    - name: Upload macOS Application
      uses: actions/upload-artifact@v3
      with:
        name: akio-local-engine-macos
        path: ./dist/akio-local-engine
